BEGIN;

CREATE INDEX agent_credentials_workspace_fk
  ON agent_credentials (workspace_id);
CREATE INDEX agent_credentials_identity_fk
  ON agent_credentials (agent_identity_id);
CREATE INDEX device_authorizations_workspace_fk
  ON device_authorizations (workspace_id);
CREATE INDEX device_authorizations_identity_fk
  ON device_authorizations (agent_identity_id);
CREATE INDEX device_flow_requests_workspace_fk
  ON device_flow_requests (workspace_id);
CREATE INDEX device_flow_requests_identity_fk
  ON device_flow_requests (agent_identity_id);
CREATE INDEX agent_sessions_identity_fk
  ON agent_sessions (agent_identity_id);
CREATE INDEX agent_sessions_credential_fk
  ON agent_sessions (credential_id);
CREATE INDEX agent_sessions_device_fk
  ON agent_sessions (device_authorization_id);
CREATE INDEX work_threads_creator_identity_fk
  ON work_threads (created_by_agent_identity_id);
CREATE INDEX work_thread_grants_identity_fk
  ON work_thread_agent_grants (agent_identity_id);
CREATE INDEX work_thread_grants_handoff_fk
  ON work_thread_agent_grants (granted_by_handoff_id);
CREATE INDEX source_events_work_thread_fk
  ON source_events (work_thread_id);
CREATE INDEX source_events_identity_fk
  ON source_events (agent_identity_id);
CREATE INDEX source_events_session_fk
  ON source_events (agent_session_id);
CREATE INDEX context_items_work_thread_fk
  ON context_items (work_thread_id);
CREATE INDEX context_items_creator_identity_fk
  ON context_items (created_by_agent_identity_id);
CREATE INDEX handoffs_work_thread_fk
  ON handoffs (work_thread_id);
CREATE INDEX handoffs_from_identity_fk
  ON handoffs (from_agent_identity_id);
CREATE INDEX handoffs_to_identity_fk
  ON handoffs (to_agent_identity_id);
CREATE INDEX handoffs_claimed_session_fk
  ON handoffs (claimed_by_session_id);
CREATE INDEX context_receipts_work_thread_fk
  ON context_receipts (work_thread_id);
CREATE INDEX context_receipts_identity_fk
  ON context_receipts (agent_identity_id);
CREATE INDEX context_receipts_session_fk
  ON context_receipts (agent_session_id);
CREATE INDEX outcomes_work_thread_fk
  ON outcomes (work_thread_id);
CREATE INDEX outcomes_receipt_fk
  ON outcomes (receipt_id);
CREATE INDEX outcomes_identity_fk
  ON outcomes (agent_identity_id);
CREATE INDEX outcomes_session_fk
  ON outcomes (agent_session_id);
CREATE INDEX corrections_workspace_fk
  ON corrections (workspace_id);
CREATE INDEX corrections_work_thread_fk
  ON corrections (work_thread_id);
CREATE INDEX corrections_context_item_fk
  ON corrections (context_item_id);
CREATE INDEX jobs_workspace_fk
  ON jobs (workspace_id);
CREATE INDEX context_item_restrictions_identity_fk
  ON context_item_agent_restrictions (agent_identity_id);
CREATE INDEX work_thread_links_source_fk
  ON work_thread_links (source_work_thread_id);
CREATE INDEX work_thread_links_target_fk
  ON work_thread_links (target_work_thread_id);

COMMIT;
